service: watchdog-data-stream

frameworkVersion: '3'

custom: ${file(./.env.yml)}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.${opt:stage, 'dev'}.profile}
  runtime: python3.9
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  environment:
    ENV: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds: ${self:custom.${opt:stage, 'dev'}.vpc_security_group_ids}
    subnetIds: ${self:custom.${opt:stage, 'dev'}.vpc_subnet_ids}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:ListSecrets
            - kms:Decrypt
            - secretsmanager:DescribeSecret
            - secretsmanager:GetSecretValue
          Resource:
          - "arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${opt:stage}/RDS/DATABASE_URL*"
          - "arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${opt:stage}/RDS/data_stream*"

functions:
  simulator:
    handler: src/handler.data_simulator
    timeout: 300
    memorySize: 128
    events:
      - schedule:
          rate: rate(6 minutes)
          enabled: false

  configureDB:
    handler: src/handler.configure_db
    timeout: 300
    memorySize: 128
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: false

  transactionLog:
    handler: src/handler.run
    events:
      - eventBridge:
          enabled: true
          pattern:
            source:
              - 'aws.cloudwatch'
            detail-type:
              - 'CloudWatch Alarm State Change'
            resources:
              - "arn:aws:cloudwatch:${aws:region}:${aws:accountId}:alarm:awsrds-${self:custom.${opt:stage, 'dev'}.database_instance_name}-High-Transaction-Logs-Disk-Usage"
#OPTION 2
#            detail:
#              alarmName": "awsrds-${self:custom.${opt:stage, 'dev'}.database_instance_name}-High-Transaction-Logs-Disk-Usage"

    timeout: 15  # in seconds

resources:
  Resources:
    TransactionLogDiskAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: awsrds-${self:custom.${opt:stage, 'dev'}.database_instance_name}-High-Transaction-Logs-Disk-Usage
        ActionsEnabled: true
        OKActions: [ ]
        AlarmActions: [ ]
        InsufficientDataActions: [ ]
        MetricName: TransactionLogsDiskUsage
        Namespace: AWS/RDS
        Statistic: Average
        Dimensions:
          - Name: DBInstanceIdentifier
            Value: ${self:custom.${opt:stage, 'dev'}.database_instance_name}
        Period: 60
        EvaluationPeriods: 10
        DatapointsToAlarm: 10
        Threshold: 3000000000
        ComparisonOperator: GreaterThanOrEqualToThreshold
#creating the custom VPC Endpoint
    SMInterfaceEndpoint:
      Type: 'AWS::EC2::VPCEndpoint'
      Properties:
        VpcEndpointType: Interface
        ServiceName: 'com.amazonaws.${aws:region}.secretsmanager'
        PrivateDnsEnabled: true
        VpcId: ${self:custom.${opt:stage, 'dev'}.vpc_id}
        SubnetIds: ${self:custom.${opt:stage, 'dev'}.vpc_subnet_ids}
        SecurityGroupIds: ${self:custom.${opt:stage, 'dev'}.vpc_security_group_ids}

package:
  exclude:
    - .env.*
    - node_modules/**

plugins:
  - serverless-python-requirements
